### ISSUE TITLE
pre-existing data

### ISSUE THREAD

**Issue by mtsmachado8** [VassilisPallas/mongoose-fuzzy-searching#30]
Hi, thanks for the great plugin.
I've used pre-existing data update differently tough.
It uses Promise.all to update docs in database instead of async and queue from async as

follows:
```
const updateFuzzy = async (Model, attrs) => {
   const docs = await Model.find();

   const updateToDatabase = async data => {
      try {
         if(attrs && attrs.length) {
            const obj = attrs.reduce((acc, attr) => ({ ...acc, [attr]: data[attr] }), {});
            return Model.findByIdAndUpdate(data._id, obj).exec();
         }

         return Model.findByIdAndUpdate(data._id, data).exec();
      } catch (e) {
         console.error(e);
      }
   };

   await Promise.all(docs.map(doc => updateToDatabase(doc)));
}

// usage
updateFuzzy(User, ['firstName']);
```
can you consider it to update docs?
i've also tried to contribute with your project but count find a CONTRIBUTING.md and i dont have permissions to create branchs and create pull requests...
Can you also consider adding it?
thx, very much, hope hearing from you soon.

**Comment by VassilisPallas** [comment]
Hello @mtsmachado8 ,

Thanks for the update, it looks great! 
Did you try to fork the repository and then make a pull request from there? Take a look at [this page](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork), and if you are still facing problems please let me know to sort it out. Also, I will create `CONTRIBUTING.md` as soon as possible.

**Comment by Kuzzy** [comment]
`const docs = await Model.find();`

It will crash because out of memory on large data sets because whole collection will be loaded into the memory. Cursor should be used instead, something like this:

```javascript
const updateFuzzy = async (Model, attrs) => {
    for await (const doc of Model.find()) {
      if (attrs && attrs.length) {
        // eslint-disable-next-line no-loop-func
        const obj = attrs.reduce((acc, attr) => ({ ...acc, [attr]: doc[attr] }), {})
        await Model.findByIdAndUpdate(doc._id, obj) // No need to exec here, because of await
      }
    }
  }
``` 

Check this article: [Async Iterators With Mongoose Queries](http://thecodebarbarian.com/whats-new-in-mongoose-53-async-iterators.html)

Also, I'm not sure for what this line after `if` condition:

```javascript
return Model.findByIdAndUpdate(data._id, data).exec();
```

Looks like it will update every record in collection, but it has no sense because `createByFieldType` function fill iterate through passed attrs and in this case will do nothing. Also, be careful with production data, if you use timestamps in your schema 'updatedAt' field will be updated after `Model.findByIdAndUpdate`
