### ISSUE TITLE
Access confidence score

### ISSUE THREAD

**Issue by CaiProgramming** [VassilisPallas/mongoose-fuzzy-searching#31]
The confidence score for some reason isnt accessible from the array of objects it returns.
my code:
```
  await Card.fuzzySearch({ query: req.params.name, limit: 10 })
    .then(card => {
      for (let i = 0; i < card.length; i++) {
        console.log(card[i].confidenceScore);
      }
      cards = card;
    });
```

**Comment by VassilisPallas** [comment]
Hi @CaiProgramming. Sometimes the `confidenceScore` isn't inside the document. I still don't know the reason. For now, you should access it from the private object _doc, eg. `card[i]._doc.confidenceScore`.

**Comment by CaiProgramming** [comment]
ty bud

**Comment by CaiProgramming** [comment]
@VassilisPallas do you have any intention of doing a keyword search?

**Comment by CaiProgramming** [comment]
@VassilisPallas also confidence score does seem to be a little off. 
``` Query: Bane```
```  
        "name": "Brawl-Bash Ogre",
        "confidenceScore": 5.85,
        "id": "5d1d0b2e91fd9235c42fa86d"```

```
        "name": "Dune-Brood Nephilim \r",
        "confidenceScore": 5.85,
        "id": "5d9d457c88827a2c241dfaae"
```
```
    {
        "id": "5d9679d9751ccc189bc12be2",
        "name": "Bane of the Living",
        "confidenceScore": 5.5,
    }
```

**Comment by VassilisPallas** [comment]
This module splits the values of the selected attributes into N-grams. You should choose wisely the number if the N-grams size, otherwise the results will not be accurate. For example, on the behaviour you are facing,  if the N-gram min size is 2, the array will be this: 
```
[ne, an, ba, ane, ban, bane]
```

Therefore, the confidence level and the results don't seem to be very accurate. To avoid that you can set the `prefixOnly` boolean to true, in order the algorithm to split the value from the prefix. The previous result would be like this this options enabled:

```
[ba, ban, bane]
``` 

Also, about the keywords, you can use the `$regex` operator from Mongoose. For instance if you want to fetch the attributes by searching the name using fuzzy search and by the selected keyword, you can do something similar to this:

```
const results = await Card.fuzzySearch('Bane', {keyword: { $regex: /pattern/, $options: '<options>' }});
```

**Comment by VassilisPallas** [comment]
And one more thing. I saw you have the limit inside the query options. This module is using `Find()`, so you can do it like this:

```
const results = await Model.fuzzySearch('Bane').limit(10);
```
